repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241  # specify a version
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931  # specify a version
    hooks:
      - id: mypy
